name: kafka-local
driverClass: io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkDriver

topicConfig: ""
replicationFactor: 1

# Kafka client-specific configuration
commonConfig: |
  bootstrap.servers=44.200.168.114:80
producerConfig: ""
consumerConfig: |
  auto.offset.reset=earliest